version: "3"
services:
  beease_timer:
    restart: always
    build: ./server
    container_name: beease_timer
    ports: 
      - '8020:3001'
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: beease_timer
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
        - ./data/database:/var/lib/postgresql/data